name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # ---------------------------------------------------------
          # TEMA E BASE
          # ---------------------------------------------------------
          template: repository
          base: header, metadata
          config_timezone: America/Sao_Paulo

          plugin_introduction: yes

          # ---------------------------------------------------------
          # LANGUAGE ACTIVITY (detalhado)
          # ---------------------------------------------------------
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12
          plugin_languages_categories: programming

          # ---------------------------------------------------------
          # LINES OF CODE CHANGED
          # ---------------------------------------------------------
          plugin_lines: yes

          # ---------------------------------------------------------
          # REPOSITORY LICENSES
          # ---------------------------------------------------------
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
          plugin_licenses_ratio: yes

          # ---------------------------------------------------------
          # FEATURED REPOSITORIES
          # ---------------------------------------------------------
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator
          plugin_repositories_featured: FelipeRodrigues05/FelipeRodrigues05

          # ---------------------------------------------------------
          # COMMIT CALENDAR
          # ---------------------------------------------------------
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # ---------------------------------------------------------
          # RECENT ACTIVITY
          # ---------------------------------------------------------
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          plugin_activity_visibility: public

          # ---------------------------------------------------------
          # REPOSITORY TRAFFIC
          # ---------------------------------------------------------
          plugin_traffic: yes
