name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # ---------------------------------------------------------
          # TEMA E BASE
          # ---------------------------------------------------------
          template: repository
          base: header, metadata
          config_timezone: America/Sao_Paulo

          plugin_introduction: yes

          # ---------------------------------------------------------
          # LANGUAGE ACTIVITY (detalhado)
          # ---------------------------------------------------------
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12
          plugin_languages_categories: programming

          plugin_traffic: true
          
          # ---------------------------------------------------------
          # FEATURED REPOSITORIES
          # ---------------------------------------------------------
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator
          plugin_repositories_featured: FelipeRodrigues05/febank-backend, FelipeRodrigues05/personal-finance-app
          plugin_repositories_pinned: 5
          plugin_repositories_starred: 2
          
          # ---------------------------------------------------------
          # RECENT ACTIVITY
          # ---------------------------------------------------------
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 15
          plugin_activity_visibility: all

          plugin_isocalendar: true
          plugin_isocalendar_duration: half-year
